# Generated by Django 4.2.4 on 2023-08-30 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Category',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('is_deleted', models.BooleanField(default=False)),
				('is_published', models.BooleanField(default=True)),
				('title', models.CharField(max_length=15, unique=True)),
				('slug', models.SlugField()),
			],
			options={
				'verbose_name_plural': 'Categories',
			},
		),
		migrations.CreateModel(
			name='Post',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('is_deleted', models.BooleanField(default=False)),
				('is_published', models.BooleanField(default=True)),
				('title', models.CharField(max_length=25, unique=True)),
				('content', models.TextField()),
				('slug', models.SlugField()),
				('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
				('category', models.ManyToManyField(to='Blog.category')),
				('previous_post',
				 models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
									  to='Blog.post')),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='Comment',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('is_deleted', models.BooleanField(default=False)),
				('is_published', models.BooleanField(default=True)),
				('author', models.CharField(max_length=30)),
				('content', models.TextField()),
				('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Blog.post')),
			],
			options={
				'abstract': False,
			},
		),
	]
